# WIP: Added support for arrays of structs in ULogData derive.
This required implementing a newtype because the orphan rule forbids implementing  yule_log::macro_utils::FromField for Vec.

The case is handled when we generate `get_data_fields` by detecting when the expected return type is a Vec using the
helper fn `is_vec_of_type(ty, struct_name)`, then generating a special case line which extracts the Vec from the newtype.

⚠️This compiles but will not work.

1. The test for whether to generate the newtype  `is_vec_of_type(ty, struct_name)` is fundamentally wrong and will trigger on Vec<32> for example.
2. ```error[E0277]: the trait bound `Vec<Heartbeat>: FromField` is not satisfied
  --> core/tests/test_derive_nested.rs:39:17
   |
39 |     heartbeats: Vec<Heartbeat>,
   |                 ^^^^^^^^^^^^^^ the trait `FromField` is not implemented for `Vec<Heartbeat>`
   |
   = help: the following other types implement trait `FromField`:
             Vec<bool>
             Vec<char>
             Vec<f32>
             Vec<f64>
             Vec<i16>
             Vec<i32>
             Vec<i64>
             Vec<i8>
           and 4 others

```